version: "3"

services:
  # tick-rocks-frontend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  # env_file:
  #   - .env
  #   - .env.development
  #   depends_on:
  #     - opencrags-rest-api-dev
  #   ports:
  #     - "3000:3000"

  opencrags-rest-api-dev:
    image: opencrags/opencrags-rest-api:r35
    restart: always
    depends_on:
      - opencrags-mongo-dev
    environment:
      DB: "mongodb://opencrags-mongo-dev:27017"
    env_file:
      - .env.development
    ports:
      - "8000:8000"

  opencrags-mongo-dev:
    image: mongo:4.4.5
    restart: always
    volumes:
      - ./data:/data/db
