version: "3"

services:
  opencrags-rest-api-dev:
    image: opencrags/opencrags-rest-api:r45
    restart: always
    depends_on:
      - opencrags-mongo-dev
    environment:
      DB: "mongodb://opencrags-mongo-dev:27017"
    env_file:
      - .env.development
    ports:
      - "8000:8000"

  opencrags-mongo-dev:
    image: mongo:4.4.8
    restart: always
    volumes:
      - ./data:/data/db
