version: "3"

services:
  tick-rocks-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
      - .env.development
    ports:
      - "3000:3000"
